# Generated by Django 4.0.5 on 2022-10-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='forget_password_token',
            new_name='forgetpassword',
        ),
    ]
